// API report for @mfkit/plugin-api — generated by scripts/api-report.mjs. Do not edit.
// A change here is a change to what consumers compile against: it needs a changeset,
// and for @mfkit/plugin-api a breaking change needs a config-version bump + codemod.

// ──── index.d.ts ────────────────────────────────────────────────────────────
/**
 * Healing strategy contract — the rulebook for "what does MFKit do when an
 * MFE misbehaves at runtime?"
 *
 * Failure modes covered:
 *   - Remote fetch failure (network, 404, CORS).
 *   - Mount throwing or rejecting.
 *   - Singleton version mismatch between shell and MFE at runtime.
 *
 * The default strategy is forgiving: retry with backoff, quarantine after N
 * failures, warn on version mismatch. Enterprise consumers can swap in a
 * stricter strategy that fails fast and throws on version skew.
 */

/**
 * Decision returned from a healing hook.
 *
 *   - `retry`  — try again after `afterMs`. Counter increments.
 *   - `quarantine` — stop trying this MFE; the rest of the app keeps running.
 *   - `fail` — surface the error to the user via the outlet's error UI.
 */
type HealingDecision = {
    readonly action: "retry";
    readonly afterMs: number;
} | {
    readonly action: "quarantine";
} | {
    readonly action: "fail";
    readonly reason: string;
};
/** Severity the strategy assigns to a singleton version mismatch. */
type VersionMismatchVerdict = "warn" | "throw" | "ignore";
interface HealingContext {
    readonly entry: MFEManifestEntry;
    /** 1-indexed attempt counter — first attempt is `1`, retries grow from there. */
    readonly attempt: number;
    /** The error MFKit caught from the failing operation. */
    readonly error: Error;
}
interface VersionMismatchContext {
    /** Singleton package name (e.g. `"react"`). */
    readonly name: string;
    /** Version declared by the shell's manifest. */
    readonly expected: string;
    /** Version the MFE actually loaded. */
    readonly actual: string;
    /** The MFE that surfaced the mismatch. */
    readonly entry: MFEManifestEntry;
}
interface HealingStrategy {
    readonly id: string;
    /** Called when fetching the remote container fails. */
    readonly onLoadError: (ctx: HealingContext) => HealingDecision;
    /** Called when `mount` throws or rejects. */
    readonly onMountError: (ctx: HealingContext) => HealingDecision;
    /**
     * Called once per detected singleton version mismatch.
     * @experimental `@mfkit/kit` does not detect skew automatically yet; this
     * runs only when you call `checkSingletonVersion` from `@mfkit/kit/healing`.
     */
    readonly onVersionMismatch: (ctx: VersionMismatchContext) => VersionMismatchVerdict;
    /** Upper bound on retries before forcing quarantine. */
    readonly maxAttempts: number;
}

/**
 * Framework adapter contract.
 *
 * Each adapter teaches MFKit how to integrate a framework's build tooling
 * with Module Federation: which Vite plugins to add, which defaults to apply,
 * and how to translate manifest shared-deps into bundler-specific shape.
 *
 * Plugin-api stays bundler-agnostic — `BundlerPlugin` is generic so MFKit's
 * Vite implementation can constrain it to `vite.Plugin`, and a hypothetical
 * future Rspack adapter can do the same with its own type.
 */

/**
 * Mode the adapter is being invoked in. `dev` includes Vite's middleware
 * stack; `build` is the production bundle path.
 */
type AdapterMode = "dev" | "build";
/**
 * Context handed to the adapter when generating bundler config for a given MFE.
 */
interface FrameworkAdapterContext {
    /** The MFE the adapter is wiring. */
    readonly entry: MFEManifestEntry;
    /** Dev or production build. */
    readonly mode: AdapterMode;
    /** Absolute path the MFE will resolve relative paths from. */
    readonly cwd: string;
}
/**
 * Framework adapter contract.
 *
 * The default-shared map lets an adapter declare canonical singletons for its
 * framework (e.g. React adapter contributes `react`/`react-dom`). MFKit merges
 * these with manifest-level shared deps; per-MFE entries win on key conflict.
 */
interface FrameworkAdapter<BundlerPlugin = unknown> {
    readonly id: FrameworkId;
    /** Bundler plugins this adapter contributes for the given MFE/mode. */
    readonly plugins: (ctx: FrameworkAdapterContext) => readonly BundlerPlugin[];
    /**
     * @deprecated Ignored by `@mfkit/kit`. The shell computes every remote's URL
     * from the manifest alone (it never loads an MFE's adapter), so an
     * adapter-chosen port made the MFE serve where the shell never looked. Set
     * `port` on the manifest entry instead. Removal is a breaking change and
     * will ship with a codemod.
     */
    readonly defaultPort?: number;
    /** Adapter-supplied shared deps (e.g. React adapter shares react/react-dom). */
    readonly defaultShared?: SharedDependencyMap;
    /**
     * Extra `optimizeDeps.exclude` entries this framework needs (e.g. workspace
     * packages whose exports map confuses the dev pre-bundler).
     */
    readonly optimizeDepsExclude?: readonly string[];
}

/**
 * Template resolver contract.
 *
 * Templates are how `create-mfkit` and `mfkit add mfe` materialize a new
 * MFE's source tree. Resolvers support multiple sources — npm-published
 * packages tagged `mfkit-template`, git repos, and local paths — so internal
 * teams can ship private templates without publishing.
 *
 * Phase 2 (CLI) is the consumer of these types. Plugin-api defines the
 * contract now so plugin authors can target a stable surface.
 */

type TemplateLocatorType = "npm" | "git" | "local";
interface TemplateLocator {
    readonly type: TemplateLocatorType;
    /** Package name, git URL, or filesystem path. */
    readonly source: string;
    /** Tag, branch, commit, or version. Resolver-specific. */
    readonly ref?: string;
}
interface ResolvedTemplate {
    readonly id: string;
    readonly framework: FrameworkId;
    readonly version: string;
    /** Absolute path to the materialized template root. */
    readonly rootDir: string;
    /** Arbitrary template-supplied metadata (e.g. post-install hints). */
    readonly metadata: Readonly<Record<string, unknown>>;
}
interface TemplateResolver {
    readonly id: string;
    /** Quick predicate so the CLI can pick the right resolver. */
    readonly canResolve: (locator: TemplateLocator) => boolean;
    /** Materialize the template to disk and report what was produced. */
    readonly resolve: (locator: TemplateLocator) => Promise<ResolvedTemplate>;
}

/**
 * MFKit plugin contract — the top-level extension point.
 *
 * A plugin is a bag of optional contributions to any of the pluggable
 * surfaces. Plugins are applied in manifest order; later plugins can override
 * earlier ones for surfaces that take a single value (e.g. `healing`).
 *
 * Conceptually: plugins are the "if you ever need to do this without forking
 * MFKit, here's where you do it" escape hatch.
 */

interface MFKitPlugin {
    readonly name: string;
    readonly version?: string;
    /** Framework adapters this plugin contributes. */
    readonly frameworkAdapters?: readonly FrameworkAdapter[];
    /** Discovery strategy this plugin contributes. See `DiscoveryStrategy` for merge rules. */
    readonly discovery?: DiscoveryStrategy;
    /** Healing strategy supplied by this plugin. Later plugins win; `config.healing` wins over all. */
    readonly healing?: HealingStrategy;
    /** Template resolvers this plugin registers with the CLI. @experimental The CLI ships in Phase 2. */
    readonly templateResolvers?: readonly TemplateResolver[];
    /**
     * One-shot setup hook. Runs once after the resolved config is finalized
     * but before MFKit starts using it. Useful for side-effecting registration
     * (e.g. injecting OpenTelemetry hooks).
     *
     * Receives the resolved config (discovered entries included). Run by
     * `resolveConfig`, once per config object per process.
     */
    readonly setup?: (config: MFKitConfig) => void | Promise<void>;
}

/**
 * Manifest types — the host's declarative source of truth.
 *
 * A single `mfkit.config.ts` at the consumer's repo root declares every MFE,
 * the shell, shared dependencies, budgets, and pluggable strategies. Vite
 * configs, Turbo pipelines, route maps, and TypeScript bindings are derived
 * from this manifest. Hand-edits to generated files are explicit escape
 * hatches, not the norm.
 */

/**
 * The current MFKit config schema version. Codemods dispatch on this number;
 * bumping it requires registering a migration in `@mfkit/codemods`.
 */
declare const MFKIT_CONFIG_VERSION: 1;
/**
 * Framework identifier. Built-in adapters cover the polyglot baseline;
 * plugin authors may register additional IDs via `FrameworkAdapter`.
 *
 * The `(string & {})` intersection preserves IDE autocomplete for the literal
 * union while still admitting arbitrary plugin-supplied strings.
 */
type FrameworkId = "react" | "svelte" | "vue" | "angular" | "lit" | (string & {});
/**
 * Module Federation shared-dependency configuration, normalized for MFKit.
 *
 * Mirrors the subset of `@module-federation/vite` shape that adapters care
 * about. Adapters translate this to their underlying bundler's contract.
 */
interface SharedDependency {
    readonly singleton?: boolean;
    readonly strictVersion?: boolean;
    readonly requiredVersion?: string;
    readonly eager?: boolean;
}
/** A map of package names → shared-dep config. */
type SharedDependencyMap = Readonly<Record<string, SharedDependency>>;
/**
 * A single MFE's manifest entry — declarative, no behavior. The MFE's runtime
 * behavior is supplied separately via `defineMFE()` inside the MFE package.
 */
interface MFEManifestEntry {
    /** Module Federation remote name, e.g. `"mfe_metrics"`. Kebab-case is not allowed. */
    readonly name: string;
    /** URL segment owned by this MFE, e.g. `"/metrics"`. */
    readonly route: string;
    /** Framework this MFE is built with. Picks the adapter. */
    readonly framework: FrameworkId;
    /** Workspace-relative path to the MFE package, e.g. `"apps/mfe-metrics"`. */
    readonly path: string;
    /** Dev-server port. Omit to let MFKit auto-assign in the safe range. */
    readonly port?: number;
    /** Production origin override. Falls back to dev port when absent. */
    readonly origin?: string;
    /** Remote entry filename. Defaults to `"remoteEntry.js"`. */
    readonly remoteEntry?: string;
    /** Override the exposed module map. Defaults to `{ "./lifecycle": "./src/lifecycle.ts" }`. */
    readonly exposes?: Readonly<Record<string, string>>;
    /** Shared deps in addition to the host-level defaults. */
    readonly shared?: SharedDependencyMap;
    /** Display label shown in nav, loading, error states. Defaults to `name`. */
    readonly label?: string;
    /** Accessible description for nav tooltips and a11y. */
    readonly description?: string;
    /**
     * Per-MFE bundle budget in gzipped bytes.
     * @experimental Not yet consumed by `@mfkit/kit` — validated, but nothing enforces it yet.
     */
    readonly budgetBytes?: number;
}
/**
 * Shell configuration. The shell is the host application — it has remotes but
 * exposes nothing. Exactly one shell per manifest.
 */
interface ShellConfig {
    /** Module Federation host name. */
    readonly name: string;
    /** Workspace-relative path to the shell package. */
    readonly path: string;
    /** Shell framework. Used to pick the React/Vue/etc. outlet implementation. */
    readonly framework: FrameworkId;
    /** Shell dev-server port. Defaults to 3000. */
    readonly port?: number;
    /** Production origin override. */
    readonly origin?: string;
    /**
     * Initial bundle budget for the shell alone (no MFEs mounted).
     * @experimental Not yet consumed by `@mfkit/kit` — validated, but nothing enforces it yet.
     */
    readonly budgetBytes?: number;
    /**
     * Host-specific shared singletons (e.g. `react-router-dom`). Framework
     * baseline singletons (`react`, `react-dom`) belong to the framework
     * adapter's `defaultShared`. App-wide singletons (like `@devnexus/shared`)
     * belong on `MFKitConfig.shared`. This is for shell-only host deps.
     */
    readonly shared?: SharedDependencyMap;
}
/**
 * The root MFKit configuration object. Authored as `mfkit.config.ts` via
 * `defineConfig()` from `@mfkit/kit`.
 */
interface MFKitConfig {
    /** Schema version. Required so codemods can migrate forward. */
    readonly version: typeof MFKIT_CONFIG_VERSION;
    /** Host project name — surfaces in logs, manifest filenames, build output. */
    readonly name: string;
    /** The shell host. Exactly one. */
    readonly shell: ShellConfig;
    /** All federated MFEs. Order is insignificant; routes resolve via `route`. */
    readonly mfes: readonly MFEManifestEntry[];
    /** Shared deps every MFE inherits. Per-MFE entries override individual keys. */
    readonly shared?: SharedDependencyMap;
    /**
     * Optional bundle budgets. Keys are scope identifiers (e.g. `"shell-initial"`).
     * @experimental Not yet consumed by `@mfkit/kit` — validated, but nothing enforces it yet.
     */
    readonly budgets?: Readonly<Record<string, number>>;
    /**
     * Healing strategy override. Defaults to MFKit's forgiving strategy.
     * Read by `<MFKitProvider config={…}>`, `resolveConfig`, and
     * `resolveHealingStrategy`; wins over any plugin-supplied strategy.
     */
    readonly healing?: HealingStrategy;
    /**
     * Extra discovery strategy, run before plugin strategies. Discovered
     * entries are added to `mfes`; declared entries are never replaced.
     */
    readonly discovery?: DiscoveryStrategy;
    /**
     * Plugins extend any of the pluggable surfaces. Applied in order; for
     * single-value surfaces (healing) later plugins win, and the config's own
     * value wins over every plugin.
     */
    readonly plugins?: readonly MFKitPlugin[];
}

/**
 * Discovery strategy contract.
 *
 * Discovery is how MFKit finds the canonical list of MFEs at a given moment.
 * The default strategy reads `mfkit.config.ts`. Alternative strategies can
 * augment or replace it: glob the `apps/*` directory, query an npm registry
 * for `mfkit-template`-tagged packages, fetch from a federation graph API.
 *
 * Multiple strategies compose: `config.discovery` runs first, then each
 * plugin's in order. Discovered entries are *added* to the manifest; an entry
 * whose `name` the manifest already declares is ignored (user-declared values
 * always win). Among discovered entries, a later strategy wins a name tie.
 * The merged list is validated like a hand-written manifest. Run by
 * `resolveConfig` (`@mfkit/kit`) at build time, so strategies may use the
 * filesystem.
 */

interface DiscoveryContext {
    /** Absolute path of the consumer's workspace root. */
    readonly cwd: string;
    /** The static manifest. Strategies may augment but should not mutate. */
    readonly config: MFKitConfig;
}
interface DiscoveryStrategy {
    /** Stable identifier — used in logs, plugin ordering, dedup. */
    readonly id: string;
    /** Returns the MFE entries this strategy contributes for the given context. */
    readonly discover: (ctx: DiscoveryContext) => Promise<readonly MFEManifestEntry[]>;
}

/**
 * MFE lifecycle contract — the one shape every MFE exposes.
 *
 * MFKit injects an `MFEContext` separate from user-defined `props`. Context
 * is MFKit's channel (route, mount ID, abort signal); props are arbitrary
 * payload supplied by the host. Keeping them distinct lets MFKit add context
 * fields without breaking host/MFE prop schemas.
 */
/**
 * MFKit-injected context, passed to `mount` on every mount.
 *
 * Implementations should:
 *   - Use `basePath` for client-side routing inside the MFE.
 *   - Honor `signal` — if it aborts during async setup, mount should resolve
 *     without rendering.
 */
interface MFEContext {
    /** URL segment the MFE is mounted under, e.g. `"/metrics"`. */
    readonly basePath: string;
    /** Unique ID per mount instance — useful for keying per-mount state. */
    readonly mountId: string;
    /** Aborts when the host unmounts the MFE before `mount` resolves. */
    readonly signal: AbortSignal;
}
/**
 * The contract every MFE exposes as its default export from `lifecycle.ts`.
 *
 * `Props` is generic so MFEs can declare strongly-typed payloads; the default
 * `unknown` enforces a guard at the boundary when consumers don't specify.
 *
 * Both `mount` and `unmount` may be sync or async. The host awaits both.
 */
interface MFEDefinition<Props = unknown> {
    readonly mount: (el: HTMLElement, ctx: MFEContext, props?: Props) => Promise<void> | void;
    readonly unmount: (el: HTMLElement) => Promise<void> | void;
}
/**
 * Backwards-compatible alias preserving the original `MFELifecycle` name used
 * across the design docs and DevNexus. Treated as identical to `MFEDefinition`.
 */
type MFELifecycle<Props = unknown> = MFEDefinition<Props>;

/**
 * Outlet contract — framework-agnostic props shared by every host-side outlet
 * implementation (React's `<MFKitOutlet>`, future Vue/Svelte/etc.).
 *
 * Framework-specific subtypes (e.g. `MFKitOutletProps` in `@mfkit/kit/react`)
 * extend this base with framework-native fallback types (`ReactNode`, etc.).
 * Keeping the base agnostic means plugin-api never depends on a UI framework.
 */

interface MFKitOutletPropsBase {
    /** MF remote name to load, e.g. `"mfe_metrics"`. */
    readonly remote: string;
    /** Exposed module path, defaults to `"lifecycle"`. */
    readonly module?: string;
    /** Route prefix passed to the MFE's `MFEContext.basePath`. */
    readonly basePath?: string;
    /** Arbitrary props forwarded to the MFE's `mount(el, ctx, props)`. */
    readonly props?: Readonly<Record<string, unknown>>;
    /** Override the host-default healing strategy for this single outlet. */
    readonly healing?: HealingStrategy;
    /** Fires once the MFE reports `mount` resolved successfully. */
    readonly onMount?: () => void;
    /** Fires when `unmount` resolves. */
    readonly onUnmount?: () => void;
    /** Fires on any error — load, mount, or version mismatch. */
    readonly onError?: (err: Error) => void;
}

export { type AdapterMode, type DiscoveryContext, type DiscoveryStrategy, type FrameworkAdapter, type FrameworkAdapterContext, type FrameworkId, type HealingContext, type HealingDecision, type HealingStrategy, type MFEContext, type MFEDefinition, type MFELifecycle, type MFEManifestEntry, MFKIT_CONFIG_VERSION, type MFKitConfig, type MFKitOutletPropsBase, type MFKitPlugin, type ResolvedTemplate, type SharedDependency, type SharedDependencyMap, type ShellConfig, type TemplateLocator, type TemplateLocatorType, type TemplateResolver, type VersionMismatchContext, type VersionMismatchVerdict };
