// Pure derivation: MFKitConfig → ambient .d.ts text declaring every federated
// remote module the shell can import. Emits one `declare module` block per
// MFE × expose key, typed as `MFEDefinition` from @mfkit/plugin-api.
//
// The whole point of these declarations is that they exist regardless of
// whether the remote bundle has been built. The shell typechecks against the
// contract; that is the "placeholder when remote unavailable" surface called
// out in the Phase 1 plan.
//
// No file I/O. No bundler/UI imports. Pure node, tree-shakable in isolation.

import type { MFKitConfig, MFEManifestEntry } from "@mfkit/plugin-api";

import { MFKitConfigError } from "../index.js";

const DEFAULT_BANNER = [
  "// AUTO-GENERATED by @mfkit/kit/types — do not edit by hand.",
  "// Regenerated from mfkit.config.ts; rerun your sync (or watcher) to refresh.",
].join("\n");

const DEFAULT_EXPOSE_KEY = "./lifecycle";

export interface GenerateRemoteTypesOptions {
  /** Banner comment placed at the top of the file. */
  readonly banner?: string;
  /**
   * Package the `MFEDefinition` type is imported from inside each declaration.
   * Defaults to `"@mfkit/plugin-api"`. Override if the consumer re-exports
   * the type from somewhere else (e.g. their own type barrel).
   */
  readonly contractPackage?: string;
}

/**
 * Generate the ambient `.d.ts` source that declares every federated module
 * exposed by the manifest. Returns the file contents as a string; the
 * consumer is responsible for writing it (see `writeRemoteTypes`).
 *
 * Output is deterministic: identical input → identical string, byte-for-byte.
 * MFEs are emitted in manifest order; exposes are emitted in object-key
 * order. The trailing newline is included so downstream formatters/diffs
 * stay stable.
 */
export function generateRemoteTypes(
  config: MFKitConfig,
  opts: GenerateRemoteTypesOptions = {},
): string {
  if (!config || typeof config !== "object" || !Array.isArray(config.mfes)) {
    throw new MFKitConfigError(
      "generateRemoteTypes: expected a validated MFKitConfig (call defineConfig first).",
      [{ path: "<root>", message: "config must be an MFKitConfig object" }],
    );
  }

  const banner = opts.banner ?? DEFAULT_BANNER;
  const contractPkg = opts.contractPackage ?? "@mfkit/plugin-api";

  const blocks: string[] = [];
  for (const mfe of config.mfes) {
    for (const exposeKey of resolveExposeKeys(mfe)) {
      blocks.push(renderModuleBlock(mfe.name, exposeKey, contractPkg));
    }
  }

  // Empty manifest still emits a valid (empty) declaration file. `export {}`
  // keeps TS treating it as a module rather than a script.
  const body = blocks.length > 0 ? blocks.join("\n\n") : "export {};";

  return `${banner}\n\n${body}\n`;
}

function resolveExposeKeys(mfe: MFEManifestEntry): readonly string[] {
  if (mfe.exposes === undefined) return [DEFAULT_EXPOSE_KEY];
  const keys = Object.keys(mfe.exposes);
  return keys.length > 0 ? keys : [DEFAULT_EXPOSE_KEY];
}

function renderModuleBlock(
  mfeName: string,
  exposeKey: string,
  contractPkg: string,
): string {
  const moduleSpecifier = `${mfeName}/${stripExposePrefix(exposeKey)}`;
  return [
    `declare module "${moduleSpecifier}" {`,
    `  import type { MFEDefinition } from "${contractPkg}";`,
    `  const lifecycle: MFEDefinition;`,
    `  export default lifecycle;`,
    `}`,
  ].join("\n");
}

function stripExposePrefix(key: string): string {
  // Expose keys follow MF convention: "./lifecycle", "./components/Button".
  // The federated module specifier the shell imports drops the leading "./".
  return key.startsWith("./") ? key.slice(2) : key;
}
