#!/usr/bin/env node
// L2 API report (docs/testing-and-evaluation.md): the public type surface of
// every published package, committed as `packages/<pkg>/api-report.d.ts`.
//
//   pnpm api:update   regenerate after an intentional API change
//   pnpm api:check    CI — fails if the built surface differs from the report
//
// Turns invariant 1 ("breaking plugin-api bumps the config version and needs
// a codemod") from a review rule into a diff a reviewer can't miss. Reads the
// built `dist/*.d.ts` (run `pnpm build` first). Internal adapter chunks are
// excluded; shared declaration chunks are included with their content hash
// normalized, so only real surface changes show up.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const PACKAGES = ["plugin-api", "kit", "codemods"];
const check = process.argv.includes("--check");

// Rollup chunk names are `<name>-<8-char hash>`.
const HASHED = /^(.*)-[\w-]{8}$/u;

function report(pkg) {
  const dist = join(root, "packages", pkg, "dist");
  const files = readdirSync(dist)
    .filter((f) => f.endsWith(".d.ts"))
    .sort();
  const rename = new Map();
  for (const f of files) {
    const base = f.slice(0, -".d.ts".length);
    const m = HASHED.exec(base);
    if (m && !isEntry(pkg, base)) rename.set(base, `${m[1]}-[hash]`);
  }
  const normalize = (text) => {
    let out = text.replace(/^\/\/# sourceMappingURL=.*$/gmu, "").trimEnd();
    for (const [from, to] of rename) out = out.split(from).join(to);
    return out;
  };
  const sections = files.map((f) => {
    const name = rename.get(f.slice(0, -".d.ts".length));
    const label = name ? `${name}.d.ts` : f;
    return `// ──── ${label} ${"─".repeat(Math.max(0, 70 - label.length))}\n${normalize(readFileSync(join(dist, f), "utf8"))}\n`;
  });
  return `// API report for @mfkit/${pkg} — generated by scripts/api-report.mjs. Do not edit.\n// A change here is a change to what consumers compile against: it needs a changeset,\n// and for @mfkit/plugin-api a breaking change needs a config-version bump + codemod.\n\n${sections.join("\n")}`;
}

function isEntry(pkg, base) {
  const exportsMap = JSON.parse(
    readFileSync(join(root, "packages", pkg, "package.json"), "utf8"),
  ).exports;
  return Object.values(exportsMap).some((e) => e.types === `./dist/${base}.d.ts`);
}

const stale = [];
for (const pkg of PACKAGES) {
  const path = join(root, "packages", pkg, "api-report.d.ts");
  const next = report(pkg);
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // first run
  }
  if (current === next) continue;
  if (check) stale.push(`packages/${pkg}/api-report.d.ts`);
  else {
    writeFileSync(path, next);
    console.log(`updated packages/${pkg}/api-report.d.ts`);
  }
}

if (check) {
  if (stale.length > 0) {
    console.error(
      `Public API changed:\n  ${stale.join("\n  ")}\n\n` +
        "If intended: run `pnpm build && pnpm api:update`, commit the report, and add a changeset.\n" +
        "Changing @mfkit/plugin-api incompatibly also needs an MFKIT_CONFIG_VERSION bump and a codemod.",
    );
    process.exit(1);
  }
  console.log("API reports up to date.");
}
