// API report for @mfkit/kit — generated by scripts/api-report.mjs. Do not edit.
// A change here is a change to what consumers compile against: it needs a changeset,
// and for @mfkit/plugin-api a breaking change needs a config-version bump + codemod.

// ──── healing.d.ts ──────────────────────────────────────────────────────────
import { MFEManifestEntry, HealingStrategy, HealingDecision, VersionMismatchVerdict, VersionMismatchContext, MFKitConfig } from '@mfkit/plugin-api';
import { a as QuarantineRegistry } from './quarantine-[hash].js';
export { Q as QuarantineRecord, b as QuarantineRegistryOptions, c as createQuarantineRegistry } from './quarantine-[hash].js';

/** One registered remote, as the MF runtime reports it. */
interface FederationRemoteLike {
    readonly name: string;
    readonly entry?: string;
}
/**
 * The slice of `@module-federation/runtime` the loader needs. Method syntax on
 * purpose: it keeps the real runtime's (generic, wider) signatures assignable.
 */
interface FederationRuntimeLike {
    loadRemote(id: string): Promise<unknown>;
    registerRemotes(remotes: FederationRemoteLike[], options?: {
        force?: boolean;
    }): void;
    getInstance(): {
        readonly options: {
            readonly remotes: readonly FederationRemoteLike[];
        };
    } | null;
}
/**
 * Wrap the MF runtime's `loadRemote` so a load that follows a failure of the
 * same remote re-fetches its entry instead of replaying the cached failure.
 * Hand the result to `<MFKitProvider loadRemote={…}>`.
 */
declare function createFederationLoader(runtime: FederationRuntimeLike): (id: string) => Promise<unknown>;

interface ManifestStorage {
    get(key: string): string | null | undefined | Promise<string | null | undefined>;
    set(key: string, value: string): void | Promise<void>;
    remove(key: string): void | Promise<void>;
}
declare function memoryManifestStorage(): ManifestStorage;
interface ManifestCacheOptions {
    readonly storage?: ManifestStorage;
}
interface ManifestLoadResult<T> {
    readonly value: T;
    /** True when the live fetch failed and a cached value was served instead. */
    readonly stale: boolean;
    /** Original fetch error; only present when `stale` is true. */
    readonly error?: Error;
}
interface ManifestCache<T> {
    load(key: string, fetcher: () => Promise<T>): Promise<ManifestLoadResult<T>>;
    invalidate(key: string): Promise<void>;
}
declare function createManifestCache<T>(opts?: ManifestCacheOptions): ManifestCache<T>;

type HealingOpKind = "load" | "mount";
interface RunWithHealingOptions<T> {
    readonly op: () => Promise<T>;
    readonly entry: MFEManifestEntry;
    readonly kind: HealingOpKind;
    readonly strategy: HealingStrategy;
    readonly registry?: QuarantineRegistry;
    readonly signal?: AbortSignal;
    /** Fires before each retry wait so UI can surface a countdown. */
    readonly onRetry?: (decision: Extract<HealingDecision, {
        action: "retry";
    }>, error: Error) => void;
}
declare class MFEHealingError extends Error {
    readonly name = "MFEHealingError";
    readonly entryName: string;
    readonly cause: Error;
    constructor(entryName: string, message: string, cause: Error);
}
declare class MFEQuarantinedError extends Error {
    readonly name = "MFEQuarantinedError";
    readonly entryName: string;
    /** Why the MFE was quarantined — the triggering error's message. */
    readonly reason: string;
    readonly cause?: Error;
    constructor(entryName: string, reason: string, cause?: Error);
}
declare function runWithHealing<T>(opts: RunWithHealingOptions<T>): Promise<T>;

interface ForgivingStrategyOptions {
    /** Total attempts including the first. Defaults to 3. */
    readonly maxAttempts?: number;
    /** Delay before the second attempt in ms. Doubles each retry. Defaults to 200. */
    readonly initialDelayMs?: number;
    /** Upper bound on any single retry delay in ms. Defaults to 5000. */
    readonly maxDelayMs?: number;
    /** Verdict for singleton version skew. Defaults to "warn". */
    readonly onVersionMismatch?: VersionMismatchVerdict;
    /** Strategy id surfaced in logs and telemetry. */
    readonly id?: string;
}
declare function forgivingStrategy(opts?: ForgivingStrategyOptions): HealingStrategy;
interface StrictStrategyOptions {
    readonly id?: string;
    readonly onVersionMismatch?: VersionMismatchVerdict;
}
declare function strictStrategy(opts?: StrictStrategyOptions): HealingStrategy;

declare class SingletonVersionError extends Error {
    readonly name = "SingletonVersionError";
    readonly pkg: string;
    readonly expected: string;
    readonly actual: string;
    readonly entryName: string;
    constructor(ctx: VersionMismatchContext);
}
declare function checkSingletonVersion(strategy: HealingStrategy, ctx: VersionMismatchContext): VersionMismatchVerdict;

/**
 * The strategy a consumer's config declares: `config.healing`, else the last
 * plugin that supplies one (later plugins win), else `forgivingStrategy()`.
 * Same precedence as `resolveConfig`, but synchronous and dependency-free so
 * a browser shell can call it on the manifest it imports.
 */
declare function resolveHealingStrategy(config: MFKitConfig): HealingStrategy;

export { type FederationRemoteLike, type FederationRuntimeLike, type ForgivingStrategyOptions, type HealingOpKind, MFEHealingError, MFEQuarantinedError, type ManifestCache, type ManifestCacheOptions, type ManifestLoadResult, type ManifestStorage, QuarantineRegistry, type RunWithHealingOptions, SingletonVersionError, type StrictStrategyOptions, checkSingletonVersion, createFederationLoader, createManifestCache, forgivingStrategy, memoryManifestStorage, resolveHealingStrategy, runWithHealing, strictStrategy };

// ──── index.d.ts ────────────────────────────────────────────────────────────
import { MFKitConfig, MFEManifestEntry, HealingStrategy, FrameworkAdapter, MFEDefinition } from '@mfkit/plugin-api';
export * from '@mfkit/plugin-api';

interface ResolvedMFKitConfig extends MFKitConfig {
    /** Manifest entries plus everything discovery contributed. */
    readonly mfes: readonly MFEManifestEntry[];
    /**
     * The strategy in effect: `config.healing`, else the last plugin's
     * `healing`, else undefined (consumers fall back to `forgivingStrategy()`).
     */
    readonly healing?: HealingStrategy;
    /** Adapters from plugins, highest precedence first (later plugins win). */
    readonly adapters: readonly FrameworkAdapter[];
    /** Names of entries that came from discovery rather than the manifest. */
    readonly discovered: readonly string[];
}
interface ResolveConfigOptions {
    /** Workspace root handed to discovery strategies. Defaults to process.cwd(). */
    readonly cwd?: string;
}
/** Resolve (once per config object) the manifest every MFKit consumer uses. */
declare function resolveConfig(config: MFKitConfig, opts?: ResolveConfigOptions): Promise<ResolvedMFKitConfig>;

interface MFKitConfigIssue {
    /** Dot-path to the offending field, e.g. "mfes[0].port". */
    readonly path: string;
    readonly message: string;
}
declare class MFKitConfigError extends Error {
    readonly name = "MFKitConfigError";
    readonly issues: readonly MFKitConfigIssue[];
    constructor(message: string, issues?: readonly MFKitConfigIssue[]);
}
/** Port the shell dev server uses when `shell.port` is omitted. */
declare const DEFAULT_SHELL_PORT = 3000;
/**
 * Author the top-level MFKit manifest. Validates the shape and cross-field
 * invariants (uniqueness of MFE name/port/route) at call time and returns
 * the input unchanged on success — `toBe` reference-equality holds.
 *
 * Aggregates every issue into one MFKitConfigError so users see all problems
 * at once instead of fixing one and discovering the next.
 */
declare function defineConfig(config: MFKitConfig): MFKitConfig;
/**
 * Stamp an MFE's runtime lifecycle with the MFKit contract. Phase 1 is a
 * typed passthrough plus shape validation — Step 5 wires every MFE through
 * this so the kit can intercept mount/unmount for healing telemetry without
 * changing behavior.
 */
declare function defineMFE<Props = unknown>(def: MFEDefinition<Props>): MFEDefinition<Props>;

export { DEFAULT_SHELL_PORT, MFKitConfigError, type MFKitConfigIssue, type ResolveConfigOptions, type ResolvedMFKitConfig, defineConfig, defineMFE, resolveConfig };

// ──── quarantine-[hash].d.ts ────────────────────────────────────────────────
interface QuarantineRecord {
    readonly reason: string;
    readonly quarantinedAt: number;
    /** When the record goes half-open. Absent when the registry has no cooldown. */
    readonly retryAt?: number;
}
interface QuarantineRegistry {
    /** True while the record is open (quarantined and not yet due for a probe). */
    isQuarantined(name: string): boolean;
    quarantine(name: string, reason: string): void;
    /** Lift quarantine for `name`, or all entries when called without arguments. */
    clear(name?: string): void;
    snapshot(): ReadonlyMap<string, QuarantineRecord>;
    /**
     * True when the cooldown has elapsed and the next attempt should be a single
     * probe. Optional so custom registries written before cooldowns still fit.
     */
    isHalfOpen?(name: string): boolean;
}
interface QuarantineRegistryOptions {
    /**
     * Time after which a quarantined MFE gets one probe attempt. Omit for the
     * classic behavior: quarantined until `clear()` or reload.
     */
    readonly cooldownMs?: number;
    /** Clock override for tests. Defaults to `Date.now`. */
    readonly now?: () => number;
}
declare function createQuarantineRegistry(opts?: QuarantineRegistryOptions): QuarantineRegistry;

export { type QuarantineRecord as Q, type QuarantineRegistry as a, type QuarantineRegistryOptions as b, createQuarantineRegistry as c };

// ──── react.d.ts ────────────────────────────────────────────────────────────
import { MFEManifestEntry, MFKitOutletPropsBase, HealingStrategy, MFKitConfig } from '@mfkit/plugin-api';
import { a as QuarantineRegistry } from './quarantine-[hash].js';
import { ReactNode, ReactElement } from 'react';

/**
 * Function the outlet calls to fetch a remote module. Consumers inject this
 * (typically `loadRemote` from `@module-federation/enhanced/runtime`) so the
 * kit does not hard-depend on a specific MF runtime. The argument is the
 * canonical `${remote}/${module}` ID.
 */
type LoadRemote = (id: string) => Promise<unknown>;
/** Reactive state surfaced by the outlet controller. */
type OutletState = {
    readonly kind: "idle";
} | {
    readonly kind: "loading";
    readonly attempt: number;
} | {
    readonly kind: "retrying";
    readonly attempt: number;
    readonly nextDelayMs: number;
    readonly error: Error;
} | {
    readonly kind: "mounted";
} | {
    readonly kind: "quarantined";
    readonly reason: string;
} | {
    readonly kind: "error";
    readonly error: Error;
};
interface LoadingSlotInfo {
    readonly entry: MFEManifestEntry;
    readonly attempt: number;
}
interface RetryingSlotInfo {
    readonly entry: MFEManifestEntry;
    readonly attempt: number;
    readonly nextDelayMs: number;
    readonly error: Error;
}
interface ErrorSlotInfo {
    readonly entry: MFEManifestEntry;
    readonly error: Error;
    /** Re-runs the load → mount cycle. */
    readonly retry: () => void;
}
interface QuarantinedSlotInfo {
    readonly entry: MFEManifestEntry;
    readonly reason: string;
    /** Lifts the quarantine record (if a registry is in play) and retries. */
    readonly retry: () => void;
}
type Slot<Info> = ReactNode | ((info: Info) => ReactNode);
interface MFKitOutletProps extends MFKitOutletPropsBase {
    /** Override the provider's loader. Required if no provider is in scope. */
    readonly loadRemote?: LoadRemote;
    /** Override the provider's quarantine registry. */
    readonly quarantineRegistry?: QuarantineRegistry;
    /** Override the provider's default strategy. */
    readonly healing?: HealingStrategy;
    /**
     * Full manifest entry. When omitted, the outlet looks the entry up by
     * `remote` from the provider's manifest, else synthesizes a minimal entry.
     */
    readonly entry?: MFEManifestEntry;
    /** Slot rendered while the MFE is loading or pre-mount. */
    readonly loadingFallback?: Slot<LoadingSlotInfo>;
    /** Slot rendered between retries. Defaults to the loading slot. */
    readonly retryingFallback?: Slot<RetryingSlotInfo>;
    /** Slot rendered when the strategy chose `{ action: "fail" }`. */
    readonly errorFallback?: Slot<ErrorSlotInfo>;
    /** Slot rendered once the MFE is quarantined. */
    readonly quarantinedFallback?: Slot<QuarantinedSlotInfo>;
    /** Class applied to the outer container. */
    readonly className?: string;
}

interface OutletControllerOptions {
    readonly container: HTMLElement;
    readonly entry: MFEManifestEntry;
    readonly loadRemote: LoadRemote;
    readonly strategy: HealingStrategy;
    readonly registry?: QuarantineRegistry;
    readonly basePath?: string;
    readonly module?: string;
    readonly props?: Readonly<Record<string, unknown>>;
    readonly onState: (state: OutletState) => void;
    readonly onMount?: () => void;
    readonly onUnmount?: () => void;
    readonly onError?: (err: Error) => void;
    /**
     * Optional id generator. Defaults to `crypto.randomUUID()` when available,
     * else a monotonic counter. Tests override for determinism.
     */
    readonly generateMountId?: () => string;
}
interface OutletController {
    /** Run the load → mount cycle. Cancels any prior in-flight cycle first. */
    start(): void;
    /** Tear down: aborts loading and awaits unmount on a mounted MFE. */
    stop(): Promise<void>;
}
declare function createOutletController(opts: OutletControllerOptions): OutletController;

declare function DefaultLoading(info: LoadingSlotInfo): ReactElement;
declare function DefaultRetrying(info: RetryingSlotInfo): ReactElement;
declare function DefaultError(info: ErrorSlotInfo): ReactElement;
declare function DefaultQuarantined(info: QuarantinedSlotInfo): ReactElement;

declare function MFKitOutlet(props: MFKitOutletProps): ReactElement;

interface MFKitProviderValue {
    readonly loadRemote: LoadRemote;
    readonly strategy: HealingStrategy;
    readonly registry: QuarantineRegistry;
    readonly entries: ReadonlyMap<string, MFEManifestEntry>;
}
interface MFKitProviderProps {
    /** Resolver for federation remotes — typically `loadRemote` from the MF runtime. */
    readonly loadRemote: LoadRemote;
    /**
     * The manifest. When given, `entries` defaults to `config.mfes` and
     * `strategy` to the config's healing (`config.healing`, else the last
     * plugin's, else forgiving). Explicit `entries`/`strategy` props win.
     */
    readonly config?: MFKitConfig;
    /** Host-wide default healing strategy. Defaults to the config's, else `forgivingStrategy()`. */
    readonly strategy?: HealingStrategy;
    /** Shared quarantine registry. Defaults to a fresh in-memory registry. */
    readonly registry?: QuarantineRegistry;
    /**
     * Manifest entries the provider knows about, used by outlets to resolve
     * `entry` from a `remote` prop. When omitted, outlets synthesize entries.
     */
    readonly entries?: readonly MFEManifestEntry[];
    readonly children: ReactNode;
}
declare function MFKitProvider(props: MFKitProviderProps): ReactElement;
/** Read the active provider value, or `null` when none is in scope. */
declare function useMFKitContext(): MFKitProviderValue | null;

export { DefaultError, DefaultLoading, DefaultQuarantined, DefaultRetrying, type ErrorSlotInfo, type LoadRemote, type LoadingSlotInfo, MFKitOutlet, type MFKitOutletProps, MFKitProvider, type MFKitProviderProps, type MFKitProviderValue, type OutletController, type OutletControllerOptions, type OutletState, type QuarantinedSlotInfo, type RetryingSlotInfo, createOutletController, useMFKitContext };

// ──── turbo.d.ts ────────────────────────────────────────────────────────────
import { MFKitConfig } from '@mfkit/plugin-api';

interface TurboTaskConfig {
    readonly dependsOn?: readonly string[];
    /** Persistent siblings started alongside this task (Turbo >= 2.4). */
    readonly with?: readonly string[];
    readonly outputs?: readonly string[];
    readonly cache?: boolean;
    readonly persistent?: boolean;
    readonly env?: readonly string[];
    readonly inputs?: readonly string[];
}
interface TurboConfig {
    readonly $schema: string;
    readonly ui?: "tui" | "stream";
    readonly tasks: Readonly<Record<string, TurboTaskConfig>>;
}
interface GenerateTurboConfigOptions {
    /** Directory paths in the manifest resolve from. Defaults to process.cwd(). */
    readonly cwd?: string;
    /** Override the JSON Schema URL emitted at the top. */
    readonly schemaUrl?: string;
    /** Turbo runner UI. Omit to leave the field off. */
    readonly ui?: "tui" | "stream";
    /**
     * Merged on top of the built-in base tasks (`build`/`dev`/`test`/
     * `typecheck`/`clean`). Per-key shallow-replace — supply the whole config
     * for any task you override.
     */
    readonly baseTasks?: Readonly<Record<string, TurboTaskConfig>>;
    /**
     * Generate `<shell-pkg>#dev` that starts every `<mfe-pkg>#dev` alongside it
     * (via Turbo's `with`, since persistent tasks cannot be `dependsOn` targets)
     * so `turbo run dev --filter <shell-pkg>` brings the remotes up too.
     * Defaults true.
     */
    readonly orchestrateShellDev?: boolean;
}
/**
 * Derive a turbo.json from an MFKit manifest. Pure aside from reading
 * package.json files referenced by `shell.path` and each `mfes[i].path` —
 * needed because Turbo addresses workspaces by their npm `name`, which the
 * manifest doesn't carry (adding it would bump plugin-api).
 *
 * Throws `MFKitConfigError` with a manifest-rooted path when a referenced
 * package.json is missing, unparseable, or lacks a `name`.
 */
declare function generateTurboConfig(config: MFKitConfig, opts?: GenerateTurboConfigOptions): TurboConfig;

export { type GenerateTurboConfigOptions, type TurboConfig, type TurboTaskConfig, generateTurboConfig };

// ──── types.d.ts ────────────────────────────────────────────────────────────
import { MFKitConfig } from '@mfkit/plugin-api';

interface GenerateRemoteTypesOptions {
    /** Banner comment placed at the top of the file. */
    readonly banner?: string;
    /**
     * Package the `MFEDefinition` type is imported from inside each declaration.
     * Defaults to `"@mfkit/plugin-api"`. Override if the consumer re-exports
     * the type from somewhere else (e.g. their own type barrel).
     */
    readonly contractPackage?: string;
}
/**
 * Generate the ambient `.d.ts` source that declares every federated module
 * exposed by the manifest. Returns the file contents as a string; the
 * consumer is responsible for writing it (see `writeRemoteTypes`).
 *
 * Output is deterministic: identical input → identical string, byte-for-byte.
 * MFEs are emitted in manifest order; exposes are emitted in object-key
 * order. The trailing newline is included so downstream formatters/diffs
 * stay stable.
 */
declare function generateRemoteTypes(config: MFKitConfig, opts?: GenerateRemoteTypesOptions): string;

declare const DEFAULT_REMOTE_TYPES_PATH = ".mfkit/generated/remotes.d.ts";
interface WriteRemoteTypesOptions extends GenerateRemoteTypesOptions {
    /**
     * Output file path. Resolved against `cwd` when relative. Defaults to
     * `.mfkit/generated/remotes.d.ts` — generated artifacts cluster under
     * `.mfkit/generated/` so consumers can `.gitignore` the whole tree.
     */
    readonly outFile?: string;
    /** Base directory `outFile` resolves from. Defaults to `process.cwd()`. */
    readonly cwd?: string;
}
interface WriteRemoteTypesResult {
    /** Absolute path the file was written to. */
    readonly outPath: string;
    /** The full file contents as written. */
    readonly content: string;
    /** True when the file content already matched and no write happened. */
    readonly unchanged: boolean;
}
/**
 * Generate and persist the federated remote `.d.ts`. The write is skipped
 * (and `unchanged: true` returned) when the existing file already matches
 * byte-for-byte — important for watcher loops that would otherwise feed
 * their own change events back through fs.watch.
 */
declare function writeRemoteTypes(config: MFKitConfig, opts?: WriteRemoteTypesOptions): Promise<WriteRemoteTypesResult>;

interface WatchRemoteTypesOptions extends WriteRemoteTypesOptions {
    /**
     * Files whose changes should trigger regeneration. Usually `mfkit.config.ts`
     * plus any imported manifest fragments. Paths resolve from `cwd`.
     */
    readonly watchPaths: readonly string[];
    /**
     * Called when any watched file changes. Should return the *current*
     * manifest. Async to accommodate dynamic-import reloads.
     */
    readonly reload: () => MFKitConfig | Promise<MFKitConfig>;
    /** Debounce window in ms (coalesces editor save-storms). Default 100. */
    readonly debounceMs?: number;
    /** Called after every successful write (including no-op). */
    readonly onWrite?: (result: WriteRemoteTypesResult) => void;
    /** Called when reload/write throws. Default: log to console.warn. */
    readonly onError?: (err: unknown) => void;
}
interface RemoteTypesWatcher {
    /** Stop watching and release fs.watch handles. */
    close(): Promise<void>;
    /** Force an immediate regenerate, bypassing the debounce. */
    trigger(): Promise<void>;
}
/**
 * Start watching the supplied source paths and regenerate the remote `.d.ts`
 * whenever any of them change. The first regeneration uses the `config`
 * passed at start; every subsequent regeneration calls `reload()` first.
 */
declare function watchRemoteTypes(config: MFKitConfig, opts: WatchRemoteTypesOptions): RemoteTypesWatcher;

export { DEFAULT_REMOTE_TYPES_PATH, type GenerateRemoteTypesOptions, type RemoteTypesWatcher, type WatchRemoteTypesOptions, type WriteRemoteTypesOptions, type WriteRemoteTypesResult, generateRemoteTypes, watchRemoteTypes, writeRemoteTypes };

// ──── vite.d.ts ─────────────────────────────────────────────────────────────
import { AdapterMode, FrameworkAdapter, MFKitConfig } from '@mfkit/plugin-api';
import { UserConfig } from 'vite';

interface MFKitViteOptions {
    /** Working directory the adapter resolves relative paths from. Defaults to process.cwd(). */
    readonly cwd?: string;
    /**
     * Workspace root handed to discovery strategies (`DiscoveryContext.cwd`).
     * Vite runs per app, so `cwd` is usually the app's folder; set this when a
     * discovery strategy scans the workspace. Defaults to `cwd`.
     */
    readonly root?: string;
    /** dev → middleware mode, fallback localhost URLs. build → production. Defaults to "build". */
    readonly mode?: AdapterMode;
    /** Adapters that win over built-ins. Useful for custom frameworks or stubbing in tests. */
    readonly adapters?: readonly FrameworkAdapter[];
    /** Print the once-per-process dev-mode inference log. Defaults true; pass false to silence it. */
    readonly logInferred?: boolean;
    /**
     * Fold an MFE's built CSS into its entry chunks so styles travel with the
     * remote instead of being stranded in an asset only its own index.html
     * references. Defaults true — federated remotes render unstyled without it.
     * Set false if the host owns all styling (e.g. a shared design-system
     * stylesheet) and you want to drop the duplicate bytes. Ignored by
     * `mfkitShell` (a shell loads its own HTML).
     */
    readonly injectCss?: boolean;
    /**
     * Module Federation share strategy for the shell. Defaults to
     * `"loaded-first"`: the shell's own singletons are used and remotes are
     * fetched only when an outlet asks for them. The MF default,
     * `"version-first"`, fetches *every* remote entry during startup to pick the
     * highest shared version — so one slow or hanging remote held the whole
     * shell's first render hostage (review R10). Ignored by `mfkitMFE`.
     */
    readonly shareStrategy?: "loaded-first" | "version-first";
}
declare function mfkitMFE(config: MFKitConfig, name: string, opts?: MFKitViteOptions): Promise<UserConfig>;
declare function mfkitShell(config: MFKitConfig, opts?: MFKitViteOptions): Promise<UserConfig>;

export { type MFKitViteOptions, mfkitMFE, mfkitShell };
