// API report for @mfkit/codemods — generated by scripts/api-report.mjs. Do not edit.
// A change here is a change to what consumers compile against: it needs a changeset,
// and for @mfkit/plugin-api a breaking change needs a config-version bump + codemod.

// ──── cli.d.ts ──────────────────────────────────────────────────────────────
#!/usr/bin/env node
interface CliIO {
    readonly stdout: (line: string) => void;
    readonly stderr: (line: string) => void;
    readonly cwd: string;
}
/**
 * Pure CLI entry. Returns the process exit code; the binary at the bottom of
 * this file forwards it to `process.exit`. Tests invoke `main` directly with
 * a capturing `CliIO`.
 */
declare function main(argv: readonly string[], io?: CliIO): Promise<number>;
declare function isEntrypoint(argv1: string | undefined, moduleUrl: string): boolean;

export { type CliIO, isEntrypoint, main };

// ──── index.d.ts ────────────────────────────────────────────────────────────
/**
 * A single MFKit upgrade. Each codemod migrates one schema version forward.
 *
 * `fromVersion`/`toVersion` correspond to `MFKitConfig.version` (the constant
 * `MFKIT_CONFIG_VERSION` re-exported from `@mfkit/plugin-api`). Codemods
 * dispatch on this number; the planner refuses any manifest whose
 * `toVersion !== fromVersion + 1`.
 */
interface CodemodManifest {
    /** Unique slug. Kebab-case, e.g. `"config-v1-to-v2-rename-shared"`. */
    readonly id: string;
    /** One-line description shown by `mfkit-migrate list`. */
    readonly description: string;
    /** Schema version this codemod migrates from. */
    readonly fromVersion: number;
    /** Schema version this codemod produces. Must equal `fromVersion + 1`. */
    readonly toVersion: number;
    /** Run the migration. Side-effecting when `ctx.dryRun === false`. */
    apply(ctx: MigrationContext): Promise<MigrationResult> | MigrationResult;
}
/**
 * Execution context handed to every codemod. The codemod is responsible for
 * resolving paths relative to `cwd`, respecting `dryRun`, and emitting
 * progress through `logger` rather than calling `console` directly.
 */
interface MigrationContext {
    /** Absolute path to the consumer project root. */
    readonly cwd: string;
    /** When true, no files may be written. The codemod still reports what *would* change. */
    readonly dryRun: boolean;
    /** Logger sink. Defaults to a console adapter in the CLI; tests pass a capturing logger. */
    readonly logger: MigrationLogger;
}
interface MigrationLogger {
    info(msg: string): void;
    warn(msg: string): void;
    error(msg: string): void;
}
/**
 * Structured outcome of one codemod run. `filesChanged` is the canonical
 * record consumers diff against; on dry runs it lists files that *would* be
 * written so a downstream UI can preview the change.
 */
interface MigrationResult {
    /** Codemod id that produced this result. */
    readonly id: string;
    /** Workspace-relative paths touched (or that would be touched on dry runs). */
    readonly filesChanged: readonly string[];
    /** Optional human-readable notes (deprecations, manual follow-ups, etc.). */
    readonly notes?: readonly string[];
}
/** Thrown by `registerCodemod` and `planMigration` on contract violations. */
declare class CodemodRegistryError extends Error {
    readonly name = "CodemodRegistryError";
}
/**
 * Register a codemod. Throws if `id` is already registered, if the version
 * step is not exactly one, or if either version is not a non-negative integer.
 *
 * Re-registering the same manifest object (reference-equal) under the same id
 * is a no-op — keeps hot-reload friendly without silently overwriting on
 * genuine duplicates.
 */
declare function registerCodemod(manifest: CodemodManifest): void;
/** Snapshot of all registered codemods, ordered by `fromVersion` then `id`. */
declare function listCodemods(): readonly CodemodManifest[];
/**
 * Compute the ordered codemod sequence to migrate from `from` to `to`.
 *
 * Returns `[]` when `from === to`. Throws when `from > to` (downgrade), when
 * any step has no registered codemod (gap), or when two codemods cover the
 * same step (ambiguous — the registry refuses to pick winners silently).
 */
declare function planMigration(from: number, to: number): readonly CodemodManifest[];
/**
 * Test-only escape hatch. Clears the module-level registry so a test suite
 * can start from a known state. Not part of the public contract — name is
 * double-underscored to signal that.
 */
declare function __resetRegistry(): void;

export { type CodemodManifest, CodemodRegistryError, type MigrationContext, type MigrationLogger, type MigrationResult, __resetRegistry, listCodemods, planMigration, registerCodemod };
